[package]
name = "jaegercat"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
clap = "2"
slog = {version = "2", features = ["release_max_level_debug"]}
sloggers = "0.2"
thrift_codec = "0.1"
trackable = "0.2"